Update

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -84,11 +84,14 @@ jobs:
 
   validation:
     needs: [changed-files, validate-renovate, validate-wrapper, gitleaks, ktfmt]
-    if: ${{ !cancelled() }}
+    if: always()
     runs-on: ubuntu-latest
     steps:
-      - if: ${{ contains(needs.*.result, 'failure') }}
-        run: exit 1
+      - run: |
+          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more validation jobs failed or were cancelled"
+            exit 1
+          fi
 
   check-build-logic:
     needs: validation
@@ -171,7 +174,7 @@ jobs:
       - run: ./gradlew licensee
 
   finish:
-    if: ${{ !cancelled() }}
+    if: always()
     needs:
       - validation
       - check-build-logic
@@ -182,5 +185,8 @@ jobs:
       - licensee
     runs-on: ubuntu-latest
     steps:
-      - if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
-        run: exit 1
+      - run: |
+          if [[ "${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "One or more jobs failed or were cancelled"
+            exit 1
+          fi
